esphome:
  name: heizung-controller

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional: Falls dein WLAN dynamische IPs vergibt, kannst du eine statische setzen:
  manual_ip:
    static_ip: 192.168.178.199
    gateway: 192.168.1.1
    subnet: 255.255.255.0

logger:
  level: DEBUG

external_components:
  - source: "./components"
    components: [wr3223]

uart:
  - id: uart_bus
    tx_pin: GPIO19
    rx_pin: GPIO18
    baud_rate: 9600
    data_bits: 7
    parity: EVEN
    stop_bits: 1

wr3223:
  uart_id: uart_bus

# Temperatur-Sensoren
sensor:
  - platform: wr3223
    sensors:
      - command: "T1"
        name: "Verdampfertemperatur"
      - command: "T2"
        name: "Kondensatortemperatur"
        update_interval: 15s
      - command: "T3"
        name: "Außentemperatur"
      - command: "T5"
        name: "Nach Wärmetauscher (Fortluft)"
      - command: "T6"
        name: "Zulufttemperatur"
      - command: "T8"
        name: "Nach Vorheizregister"
#binary_sensor:
#text_sensor:
