esphome:
  name: heizung-controller-20
  friendly_name: heizung-controller_2.0

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

external_components:
  - source: "./components"
 # - source: 
 #   type: git
 #   url: "https://github.com/schmurgel-tg/esphome-components"
 #   ref: "main"
    components: [wr3223]

# Enable Home Assistant API
api:
  encryption:
    key: "Bg1mLRzoqGjz44FpXNj4wLg5iIssG9N0Yjm8g6INzuY="

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heizung-Controller-20"
    password: "ImZyhAj3rZmt"

  manual_ip:
    static_ip: 192.168.178.199
    gateway: 192.168.1.1
    subnet: 255.255.255.0

uart:
  - id: uart_bus
    tx_pin: GPIO19
    rx_pin: GPIO18
    baud_rate: 9600
    data_bits: 7
    parity: EVEN
    stop_bits: 1

wr3223:
  uart_id: uart_bus

# Sensoren
sensor:
  - platform: wr3223
    sensors: # hier alle sensoren mit bekannten kommandos (diese haben standardwerte)
      T1:
        name: "Verdampfertemperatur"
      T2:
        deactivate: true
      T3:
        update_interval: "15s"
    sensors_custom: # hier eigene kommando, diese erfordern weitere angaben
      - command: "XZ"
        name: "Custom-Kommand"
        unit_of_measurement: V
        device_class: temperature


# Binär-Sensoren
binary_sensor:
  - platform: wr3223
    relais_sensors:
      zusatzheizung:
        deactivate: true # Dieser Sensor wird nicht erstellt
      kompressor:
        name: "Anderer Name"
        entity_category: "diagnostic"
        device_class: "power"  # Falls gewünscht, kann die `device_class` überschrieben werden        
      bypass:
        name: "Relais: Bypass"
        entity_category: "config"


